class MuZeroNetwork:
    def __init__(self, config):
        ...
        # Initialize representation, dynamics, and prediction networks
        ...

    def initial_inference(self, observation):
        ...
        # Produce initial hidden state, value, and policy
        ...

    def recurrent_inference(self, hidden_state, action):
        ...
        # Predict next hidden state, value, and policy
        ...
